from app.services.llm_router import call_llm
from app.schemas.code import (
    CodeGenerateRequest, CodeRefactorRequest, CodeExplainRequest,
    CodeTestRequest, CodeResponse
)
from app.models.user import User
from fastapi import HTTPException
import re
import logging

logger = logging.getLogger(__name__)

CODE_AGENT_SYSTEM_PROMPT = """You are CODE_AGENT. 

Rules:
- You ONLY handle programming-related tasks. 
- Output MUST be complete, executable code.
- NO explanations unless explicitly requested.
- NO placeholders. 
- NO pseudocode.
- Follow language best practices.
- Assume production-grade usage.

If requirements are ambiguous, make reasonable engineering assumptions and proceed."""

def validate_code_output(code: str) -> bool:
    """Ensure output is not placeholder/pseudocode"""
    forbidden_phrases = [
        "TODO", "PLACEHOLDER", "...", "pseudo", "implement later",
        "<placeholder>", "fill_in", "pass  #"
    ]
    for phrase in forbidden_phrases:
        if phrase.lower() in code.lower():
            return False
    return len(code.strip()) > 20

async def generate_code(payload: CodeGenerateRequest, user: User) -> CodeResponse:
    req = {
        "messages": [
            {"role": "system", "content": CODE_AGENT_SYSTEM_PROMPT},
            {"role": "user", "content": f"Generate code for the following task (auto-detect the appropriate programming language):\n{payload.prompt}"}
        ],
        "temperature": 0.2,
        "max_tokens": 4096
    }
    result = await call_llm("code_generate", req)
    code = result["choices"][0]["message"]["content"]
    if not validate_code_output(code):
        raise HTTPException(400, "Generated code contains placeholders or is invalid")
    logger.info(f"Code generated by {user.username}")
    return CodeResponse(result=code)

async def refactor_code(payload: CodeRefactorRequest, user: User) -> CodeResponse:
    req = {
        "messages": [
            {"role": "system", "content": CODE_AGENT_SYSTEM_PROMPT},
            {"role": "user", "content": f"Refactor this code to {payload.goal} (auto-detect language):\n\n```\n{payload.code}\n```"}
        ],
        "temperature": 0.2,
        "max_tokens": 4096
    }
    result = await call_llm("code_refactor", req)
    code = result["choices"][0]["message"]["content"]
    return CodeResponse(result=code)

async def explain_code(payload: CodeExplainRequest, user: User) -> CodeResponse:
    req = {
        "messages": [
            {"role": "system", "content": "You are an expert code explainer. Explain this code concisely."},
            {"role": "user", "content": f"Explain this code (auto-detect language):\n\n```\n{payload.code}\n```"}
        ],
        "temperature": 0.2,
        "max_tokens": 2048
    }
    result = await call_llm("code_explain", req)
    explanation = result["choices"][0]["message"]["content"]
    return CodeResponse(result=explanation)

async def generate_tests(payload: CodeTestRequest, user: User) -> CodeResponse:
     req = {
        "messages": [
            {"role": "system", "content": CODE_AGENT_SYSTEM_PROMPT},
            {"role": "user", "content": f"Generate unit tests for this code (auto-detect language):\n\n```\n{payload.code}\n```"}
        ],
        "temperature": 0.2,
        "max_tokens": 4096
    }
     result = await call_llm("test_generate", req)
     tests = result["choices"][0]["message"]["content"]
     return CodeResponse(result=tests)

